Added sides picking and folder processing
blackironj/panorama pull request #2
Opened 2024-07-20 19:47 UTC by thegalkin

Hi, added two features sides picking and folder processing.
I also had to add a uilive lib to update terminal output dynamically. 
Could you please check them and add if you find them a useful contribution. 

P.S. Sorry these are not the optimizations you included in readme but I needed them for personal usage.

2024-07-21 23:45 UTC, blackironj requested changes
Thank you for contributions!
I think it's a good feature.

please check a single comment.

2024-07-21 23:45 UTC, blackironj commented on cmd/root.go
> +				processDirectory(inDirPath, outFileDir)
you wrote the following in the flag desc in the Readme.
```
  -i, --in string    input image file path (required if --indir is not specified)
  -d, --indir string input directory path (required if --in is not specified)
```
If this is not what you intended, how about modifying codes like this?
```go
if inFilePath != "" {
     progress.totalFiles = 1
     progressSingleImage(inFilePath, outFileDir)
}  else {
    processDirectory(inDirPath, outFileDir)
}
```

2024-07-22 09:23 UTC, thegalkin commented on cmd/root.go
> +				processDirectory(inDirPath, outFileDir)
Thank you for your comment! Futhermore, I now see that there is no protection for case when both inFilePath and inDirPath are filled.
```
if inFilePath == "" && inDirPath == "" {
				er("Need an input image file path or input directory")
			}
if len(inFilePath) > 0 && len(inDirPath) > 0 {
er("Need only one path, not both")
}

			progress.startTime = time.Now()

			if inFilePath != "" {
				progress.totalFiles = 1
				processSingleImage(inFilePath, outFileDir)
			} else {
				processDirectory(inDirPath, outFileDir)
			}
```

2024-07-22 11:57 UTC, blackironj commented on cmd/root.go
> +				processDirectory(inDirPath, outFileDir)
```go
if len(inFilePath) > 0 && len(inDirPath) > 0 {
   er("Need only one path, not both")
}
```
I think that  codes what you added above are better. could you add that?

2024-07-22 23:37 UTC, blackironj approved these changes
Thank you

2024-07-22 23:38 UTC, merged

2024-07-23 06:44 UTC, thegalkin commented
Thank you too!